name: Coverage
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Coverage Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make setup-dev
    - name: Coverage Report
      run: |
        make coverage
    - name: Report Coveralls
      uses: coverallsapp/github-action@v2
