name: Mypy
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Mypy Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make setup
    - name: Analysing the code with Mypy
      run: |
        make check-mypy
