name: Publish

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        description: Bump Type
        type: choice
        options:
          - prerelease
          - patch
          - minor
          - major
        default: patch

jobs:
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup
        run: |
          make setup-dev

      - name: Bump Version
        id: bump_version
        env:
          BUMP_TYPE: ${{ github.event.inputs.bump_type }}
        run: |
          echo "Bumping type: ${{ env.BUMP_TYPE }}"
          new_version=$(semvergit -t ${{ env.BUMP_TYPE }} -v)
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          release_name: ${{ steps.bump_version.outputs.new_version }}
          body: New Release ${{ steps.bump_version.outputs.new_version }}

      - name: Build Package
        run: |
          make build

      - name: Publish To PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_USERNAME: ${{ secrets.PYPI_API_USER }}
        run: |
          make publish
